export enum Status {
    DA_CONFIGURARE = 'DA_CONFIGURARE',
    DA_ASSEGNARE = 'DA_ASSEGNARE',
    ASSEGNATO = 'ASSEGNATO',
    RICONSEGNATO = 'RICONSEGNATO',
    DA_FORMATTARE = 'DA_FORMATTARE',
    ROTTO = 'ROTTO',
    MULETTO = 'MULETTO',
  }
  